controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_trajectory_controller:
  ros__parameters:
    joints:
      - Cycloidal_Simplified_for_FEA-1_Revolute-28
      - Cycloidal_Simplified_for_FEA-2_Revolute-30
      - Secondary-Joint-Cartilage_Revolute-11
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 1.0

hand_trajectory_controller:
  ros__parameters:
    joints:
      - Openhand1.0_Hand_simplifiedmain-v1_Revolute-21
      - L1-v1_Revolute-23
      - L1-v1-1_Revolute-24
      - L2-v1_Revolute-25
      - L2-v1-1_Revolute-26
      - Openhand1.0_Hand_simplifiedmain-v1_Revolute-33
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 1.0
